### ISSUE TITLE
Fail sometimes? - VS2005 File.

### ISSUE THREAD

**Issue by ghost** [sevoku/Doxygen-VB-Filter-Old#1]
Hi,

I run the sample and works perfect, when I add a new file into VBNET folder's sample, generate all but crash and html/index.html show only the title, but not the classes or packages, some time just the files and don't get the comments and source files.

Is ready for vs 2005 and further?

Thanks a lot.

BTW Great Job

**Comment by sevoku** [comment]
I don't think that this has something to do with the VS version, since it is still the same language and the filter should be applied only on the *.vb files. Can you gist some example which fails?

**Comment by ghost** [comment]
Ok, now is working. 

I follow the _Environment setup_ steps and put the **awk** in the _INPUT_FILTER_ and Dioxygen only creates a "template" of html files.

> INPUT_FILTER           = "\path\to\gawk.exe -f \path\to\vbfilter.awk" -> **I replace the path for my installation path**

I remove the _INPUT_FILTER_ and put the _Advanced Installation_ suggested line: 

> INPUT_FILTER           = vbfilter.bat
> INPUT_FILTER           = "cd .. & vbfilter.bat" -> **on my case**

And works fine.

Thanks a lot.
